from __future__ import annotations

import json

from agent_switch.config.model import ToolSpec


def _literal(value: object) -> str:
    # JSON literals are deterministic and valid Python for strings, lists, and
    # mappings used by the generated wrapper.
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def render_wrapper_script(tool: ToolSpec, secret_file: str) -> str:
    """Render a standalone wrapper that grants only declared secrets.

    The previous shell wrapper sourced the complete secrets file with `set -a`,
    which exposed every stored credential to every MCP. This generated Python
    launcher parses the file as data, strips sensitive inherited variables, and
    adds back only the names explicitly declared by this tool.
    """

    return f'''#!/usr/bin/env python3
# Generated by Agent Switch. Do not edit; run `agent-switch reconcile`.
import os
import re
import sys

SECRET_FILE = {_literal(secret_file)}
REQUIRED = tuple({_literal(list(tool.required_secrets))})
TOOL_ENV = {_literal(dict(sorted(tool.env.items())))}
COMMAND = {_literal([tool.command, *tool.args])}
SECRET_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")
SENSITIVE_NAME = re.compile(r"(?:KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL|AUTH)", re.IGNORECASE)
SECRET_REFERENCE = re.compile(r"\\$\\{{([A-Z][A-Z0-9_]*)\\}}")


def decode_double_quoted(value):
    output = []
    index = 0
    while index < len(value):
        character = value[index]
        if character == "\\\\" and index + 1 < len(value) and value[index + 1] in ('\\\\', '"', '$', '`'):
            output.append(value[index + 1])
            index += 2
            continue
        output.append(character)
        index += 1
    return "".join(output)


def decode_value(raw):
    value = raw.strip()
    if value.startswith(("'", '"')):
        if len(value) < 2 or value[-1] != value[0]:
            raise ValueError("malformed quoted secret value")
        return value[1:-1] if value[0] == "'" else decode_double_quoted(value[1:-1])
    return value


def read_secrets(path):
    values = {{}}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            for raw_line in handle:
                line = raw_line.strip()
                if not line or line.startswith("#"):
                    continue
                if line.startswith("export "):
                    line = line[len("export "):].strip()
                if "=" not in line:
                    continue
                name, raw_value = line.split("=", 1)
                name = name.strip()
                if SECRET_NAME.fullmatch(name):
                    values[name] = decode_value(raw_value)
    except FileNotFoundError:
        pass
    return values


try:
    stored = read_secrets(SECRET_FILE)
except (OSError, UnicodeError, ValueError) as error:
    print("Agent Switch wrapper {tool.id} could not read the secret store: " + str(error), file=sys.stderr)
    raise SystemExit(78)

missing = [name for name in REQUIRED if not stored.get(name)]
if missing:
    print("Agent Switch wrapper {tool.id} missing required secret(s): " + " ".join(missing), file=sys.stderr)
    raise SystemExit(78)

environment = {{
    name: value
    for name, value in os.environ.items()
    if name not in stored and not SENSITIVE_NAME.search(name)
}}
for name in REQUIRED:
    environment[name] = stored[name]
environment.update(TOOL_ENV)


def expand_parameter(value):
    return SECRET_REFERENCE.sub(lambda match: environment.get(match.group(1), match.group(0)), value)


expanded_command = [expand_parameter(value) for value in COMMAND]

try:
    os.execvpe(expanded_command[0], expanded_command + sys.argv[1:], environment)
except FileNotFoundError:
    print("Agent Switch wrapper {tool.id} command not found: " + expanded_command[0], file=sys.stderr)
    raise SystemExit(127)
'''
